blog/config/routes.rb
Rails.application.routes.draw do
  get 'dictionary_words/spellcheck'
  get 'spellcheck/:term' => 'dictionary_words#spellcheck'

  resources :comments
  resources :blogposts
  root 'blogposts#index'

end

blog/app/models/blogpost.rb
class Blogpost < ActiveRecord::Base
  has_many :comments
end

blog/app/controllers/blogposts_controller.rb
class BlogpostsController < ApplicationController
  before_action :set_blogpost, only: [:show, :edit, :update, :destroy]

  # GET /blogposts
  # GET /blogposts.json
  def index
    @blogposts = Blogpost.all
  end

  # GET /blogposts/1
  # GET /blogposts/1.json
  def show
    @pcomments = @blogpost.comments
  end

  # GET /blogposts/new
  def new
    @blogpost = Blogpost.new
  end

  # GET /blogposts/1/edit
  def edit
  end

  # POST /blogposts
  # POST /blogposts.json
  def create
    @blogpost = Blogpost.new(blogpost_params)

    respond_to do |format|
      if @blogpost.save
        format.html { redirect_to @blogpost, notice: 'Blogpost was successfully created.' }
        format.json { render :show, status: :created, location: @blogpost }
      else
        format.html { render :new }
        format.json { render json: @blogpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogposts/1
  # PATCH/PUT /blogposts/1.json
  def update
    respond_to do |format|
      if @blogpost.update(blogpost_params)
        format.html { redirect_to @blogpost, notice: 'Blogpost was successfully updated.' }
        format.json { render :show, status: :ok, location: @blogpost }
      else
        format.html { render :edit }
        format.json { render json: @blogpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogposts/1
  # DELETE /blogposts/1.json
  def destroy
    @blogpost.destroy
    respond_to do |format|
      format.html { redirect_to blogposts_url, notice: 'Blogpost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blogpost
      @blogpost = Blogpost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blogpost_params
      params.require(:blogpost).permit(:title, :contents)
    end
end

blog/app/helpers/blogposts_helper.rb
module BlogpostsHelper
end

blog/app/views/blogposts/_form.html.erb
<%= form_for(@blogpost) do |f| %>
  <% if @blogpost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blogpost.errors.count, "error") %> prohibited this blogpost from being saved:</h2>

      <ul>
      <% @blogpost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :contents %><br>
    <%= f.text_area :contents %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

blog/app/views/blogposts/edit.html.erb
<h1>Editing blogpost</h1>

<%= render 'form' %>

<%= link_to 'Show', @blogpost %> |
<%= link_to 'Back', blogposts_path %>

blog/app/views/blogposts/index.html.erb
<h1>Listing blogposts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Contents</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogposts.each do |blogpost| %>
      <tr>
        <td><%= blogpost.title %></td>
        <td><%= blogpost.contents %></td>
        <td><%= link_to 'Show', blogpost %></td>
        <td><%= link_to 'Edit', edit_blogpost_path(blogpost) %></td>
        <td><%= link_to 'Destroy', blogpost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blogpost', new_blogpost_path %>

blog/app/views/blogposts/new.html.erb
<h1>New blogpost</h1>

<%= render 'form' %>

<%= link_to 'Back', blogposts_path %>

blog/app/views/blogposts/show.html.erb
<p id="notice"><%= notice %></p>

<H1>
  <%= @blogpost.title %>
</H1>

<div class="boxed">
<p>
  <%= @blogpost.contents %>
</p>
</div>

<table>

  <tbody>
    <% @pcomments.each do |comment| %>
      <tr>
        <td><%= comment.author %> said:</td>
        <td><%= comment.commenttext %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New Comment', new_comment_path %>
<br/>

<%= link_to 'Edit', edit_blogpost_path(@blogpost) %> |
<%= link_to 'Back', blogposts_path %>